name: "" # name of author
baseurl: "/" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
site-end-name: "" # name which is shown at the site end ("YEAR © SITE-END-NAME")
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Spline settings
use-spline: true
spline-url: ""

# Image path
image-url: ""

formsubmit-url: ""

# Build settings
markdown: kramdown
sass:
    style: :compressed

# List of social media accounts
# name: Name of the platform
# url: URL to the account
# icon: fontawesome icon of the platform (https://fontawesome.com/v5/search)
social-media:
  - name: GitHub
    url: https://github.com/divin
    icon: fab fa-github

# List of name & links for the site end
site-end:
  - text: "Terms & Privacy Policy"
    url: "/privacy"
  - text: Impress
    url: "/impress"

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag